using ApartmentManagementSystem.Data;
using ApartmentManagementSystem.ViewModels.President;
using Microsoft.EntityFrameworkCore;

namespace ApartmentManagementSystem.Features.President.Repositories;

public sealed class PresidentDashboardRepository(ApplicationDbContext context) : IPresidentDashboardRepository
{
    public async Task<PresidentDashboardViewModel> GetAsync(Guid buildingId, CancellationToken cancellationToken = default)
    {
        var name = await context.Buildings.AsNoTracking().Where(building => building.Id == buildingId).Select(building => building.Name).FirstOrDefaultAsync(cancellationToken) ?? "(Building)";
        var today = DateTime.UtcNow.Date;
        var month = new DateTime(today.Year, today.Month, 1, 0, 0, 0, DateTimeKind.Utc);
        var startMonth = month.AddMonths(-11);
        var totalCollected = await (from payment in context.ExpenseAllocationPayments.AsNoTracking() join bill in context.CommonBills.AsNoTracking() on payment.CommonBillId equals bill.Id where bill.BuildingId == buildingId select (decimal?)payment.Amount).SumAsync(cancellationToken) ?? 0m;
        var collectedThisMonth = await (from payment in context.ExpenseAllocationPayments.AsNoTracking() join bill in context.CommonBills.AsNoTracking() on payment.CommonBillId equals bill.Id where bill.BuildingId == buildingId && payment.CreatedAtUtc >= month select (decimal?)payment.Amount).SumAsync(cancellationToken) ?? 0m;
        var totalPayments = await context.ExpensePayments.AsNoTracking().Where(payment => payment.BuildingId == buildingId).Select(payment => (decimal?)payment.Amount).SumAsync(cancellationToken) ?? 0m;
        var paymentsThisMonth = await context.ExpensePayments.AsNoTracking().Where(payment => payment.BuildingId == buildingId && payment.CreatedAtUtc >= month).Select(payment => (decimal?)payment.Amount).SumAsync(cancellationToken) ?? 0m;
        var ownerRows = await (from payment in context.ExpenseAllocationPayments.AsNoTracking() join bill in context.CommonBills.AsNoTracking() on payment.CommonBillId equals bill.Id join user in context.Users.AsNoTracking() on payment.OwnerId equals user.Id where bill.BuildingId == buildingId orderby payment.CreatedAtUtc descending select new TransactionRowViewModel { OccurredAt = payment.CreatedAtUtc, Type = "OwnerPayment", Description = $"Owner {(user.Fullname ?? user.UserName)} paid for bill “{bill.Name}”.", Amount = payment.Amount, Currency = "BDT", Direction = "In" }).Take(60).ToListAsync(cancellationToken);
        var expenseRows = await context.ExpensePayments.AsNoTracking().Where(payment => payment.BuildingId == buildingId).Include(payment => payment.CommonBill).OrderByDescending(payment => payment.CreatedAtUtc).Select(payment => new TransactionRowViewModel { OccurredAt = payment.CreatedAtUtc, Type = "ExpensePayment", Description = payment.CommonBill != null ? $"Payment made for bill “{payment.CommonBill.Name}”." : "Expense payment recorded.", Amount = payment.Amount, Currency = "BDT", Direction = "Out" }).Take(60).ToListAsync(cancellationToken);
        var billRows = await context.CommonBills.AsNoTracking().Where(bill => bill.BuildingId == buildingId).OrderByDescending(bill => bill.CreatedAtUtc).Select(bill => new TransactionRowViewModel { OccurredAt = bill.CreatedAtUtc, Type = "CommonBillCreated", Description = $"Common bill created: “{bill.Name}”.", Amount = bill.TotalAmount, Currency = "BDT", Direction = "Info" }).Take(60).ToListAsync(cancellationToken);
        var entryRows = await context.EntryLogs.AsNoTracking().Where(entry => entry.BuildingId == buildingId).OrderByDescending(entry => entry.EntryTime).Select(entry => new TransactionRowViewModel { OccurredAt = DateTime.SpecifyKind(entry.EntryTime, DateTimeKind.Local).ToUniversalTime(), Type = "EntryLog", Description = $"{entry.EntryType} — {entry.Fullname}", Direction = "Info" }).Take(60).ToListAsync(cancellationToken);
        var income = await (from payment in context.ExpenseAllocationPayments.AsNoTracking() join bill in context.CommonBills.AsNoTracking() on payment.CommonBillId equals bill.Id where bill.BuildingId == buildingId && payment.CreatedAtUtc >= startMonth group payment by new { payment.CreatedAtUtc.Year, payment.CreatedAtUtc.Month } into grouped select new { grouped.Key.Year, grouped.Key.Month, Amount = grouped.Sum(item => item.Amount) }).ToListAsync(cancellationToken);
        var outgoing = await context.ExpensePayments.AsNoTracking().Where(payment => payment.BuildingId == buildingId && payment.CreatedAtUtc >= startMonth).GroupBy(payment => new { payment.CreatedAtUtc.Year, payment.CreatedAtUtc.Month }).Select(group => new { group.Key.Year, group.Key.Month, Amount = group.Sum(item => item.Amount) }).ToListAsync(cancellationToken);
        var allocations = await context.ExpenseAllocations.AsNoTracking().Include(allocation => allocation.CommonBill).Where(allocation => allocation.CommonBill!.BuildingId == buildingId).Select(allocation => new { allocation.Id, allocation.OwnerId, allocation.AmountDue, BillDate = allocation.CommonBill!.BillDate }).ToListAsync(cancellationToken);
        var paid = await context.ExpenseAllocationPayments.AsNoTracking().Join(context.CommonBills.AsNoTracking(), payment => payment.CommonBillId, bill => bill.Id, (payment, bill) => new { payment.ExpenseAllocationId, payment.Amount, bill.BuildingId }).Where(item => item.BuildingId == buildingId).GroupBy(item => item.ExpenseAllocationId).Select(group => new { group.Key, Paid = group.Sum(item => item.Amount) }).ToDictionaryAsync(item => item.Key, item => item.Paid, cancellationToken);
        decimal d0 = 0, d31 = 0, d61 = 0, d90 = 0; var dues = new Dictionary<string, decimal>();
        foreach (var allocation in allocations) { var outstanding = allocation.AmountDue - paid.GetValueOrDefault(allocation.Id); if (outstanding <= 0) continue; var days = (DateTime.Today - allocation.BillDate.Date).TotalDays; if (days <= 30) d0 += outstanding; else if (days <= 60) d31 += outstanding; else if (days <= 90) d61 += outstanding; else d90 += outstanding; dues[allocation.OwnerId] = dues.GetValueOrDefault(allocation.OwnerId) + outstanding; }
        var top = dues.OrderByDescending(item => item.Value).Take(7).ToList(); var ids = top.Select(item => item.Key).ToList(); var names = await context.Users.AsNoTracking().Where(user => ids.Contains(user.Id)).Select(user => new { user.Id, Name = (user.Fullname ?? user.UserName)! }).ToDictionaryAsync(user => user.Id, user => user.Name, cancellationToken);
        var labels = Enumerable.Range(0, 12).Select(index => startMonth.AddMonths(index).ToString("yyyy-MM")).ToList(); var ins = new decimal[12]; var outs = new decimal[12]; foreach (var row in income) { var index = (row.Year * 12 + row.Month - 1) - (startMonth.Year * 12 + startMonth.Month - 1); if (index is >= 0 and < 12) ins[index] = row.Amount; } foreach (var row in outgoing) { var index = (row.Year * 12 + row.Month - 1) - (startMonth.Year * 12 + startMonth.Month - 1); if (index is >= 0 and < 12) outs[index] = row.Amount; }
        return new PresidentDashboardViewModel { BuildingName = name, TotalBills = await context.CommonBills.CountAsync(bill => bill.BuildingId == buildingId, cancellationToken), TotalCollected = totalCollected, TotalPayments = totalPayments, CollectedThisMonth = collectedThisMonth, PaymentsThisMonth = paymentsThisMonth, TotalFlats = await context.Flats.CountAsync(flat => flat.BuildingId == buildingId, cancellationToken), OccupiedFlats = await context.TenantAssignments.AsNoTracking().Include(assignment => assignment.Flat).Where(assignment => assignment.EndDate == null && assignment.Flat!.BuildingId == buildingId).Select(assignment => assignment.FlatId).Distinct().CountAsync(cancellationToken), TodayEntries = await context.EntryLogs.CountAsync(entry => entry.BuildingId == buildingId && entry.EntryTime.Date == today, cancellationToken), Last7dEntries = await context.EntryLogs.CountAsync(entry => entry.BuildingId == buildingId && entry.EntryTime.Date >= today.AddDays(-6), cancellationToken), RecentTransactions = ownerRows.Concat(expenseRows).Concat(billRows).Concat(entryRows).OrderByDescending(row => row.OccurredAt).Take(25).ToList(), Cashflow = new CashflowChartVM { Labels = labels, In = ins.ToList(), Out = outs.ToList() }, Aging = new AgingBucketsVM { D0_30 = d0, D31_60 = d31, D61_90 = d61, D90Plus = d90 }, TopOwners = new TopOwnersVM { Labels = top.Select(item => names.GetValueOrDefault(item.Key, item.Key)).ToList(), Values = top.Select(item => item.Value).ToList() } };
    }
}
